export const ActionTypes = {
  ADD_TASK: 'ADD_TASK',

  READ_DATA: 'READ_DATA',
  READ_DATA_SUCCESS: 'READ_DATA_SUCCESS',
  READ_DATA_FAILURE: 'READ_DATA_FAILURE',
  // UPDATE_DATA: 'UPDATE_DATA',
  // DELETE_DATA: 'DELETE_DATA',
};
